<template>
  <div>
    <h2 class="section-header">
      PRZYCHODZĄC NA SESJĘ NIE MUSISZ UMIEĆ POZOWAĆ!
    </h2>
    <div class="w-full">
      <p class="mx-auto px-4 py-4 text-xl lg:px-32">
        <strong>Ponad 80% </strong>osób które widzisz na moich zdjęciach nigdy
        wcześniej nie było na profesjonalnej sesji fotograficznej!
      </p>
      <p class="mx-auto px-4 pb-8 text-xl lg:px-32">
        Pokażę Ci proste i sprawdzone na dziesiątkach klientów pozy, na których
        będziesz wyglądał najatrakcyjniej.
      </p>
    </div>
    <video class="mx-auto rounded-xl" width="600px" autoplay loop muted>
      <source src="../../resources/posing.mp4" type="video/mp4" />
    </video>
  </div>
  <div
    class="space-between grid grid-cols-1 py-8 lg:grid-flow-col lg:grid-cols-2"
  >
    <div class="mx-auto py-8">
      <img
        class="mx-auto rounded-xl shadow-2xl"
        src="../../resources/face-expression.png"
      />
      <p class="px-8 py-2 text-xl">
        Pokażę Ci jak zapanować nad swoją mimiką na zdjęciach
      </p>
    </div>
    <div class="mx-auto py-8">
      <img
        class="mx-auto rounded-xl shadow-2xl"
        src="../../resources/smirk.jpg"
      />
      <p class="px-8 py-2 text-xl">
        Nauczę Cię jak pokazywać atrakcyjne subkomunikacje na zdjęciach
      </p>
    </div>
  </div>
</template>
