<template>
	<div>
		<h1
			class="container mx-auto p-10 text-4xl font-black text-gold lg:text-6xl">
			TWOJE HOBBY POKAZANE Z NAJLEPSZEJ STRONY
		</h1>
		<div class="w-full">
			<p class="mx-auto px-48 py-5 text-xl">
				Zapomnij o nudnych zdjęciach w studiu!
			</p>
			<p class="mx-auto px-48 text-xl">
				Podczas sesji w plenerze uchwycimy Twoje pasje: sztuki walki, samochody,
				kalistenika, itp
			</p>
		</div>
	</div>
</template>
